apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: kubernetes-example-hello
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  namespace: default
  labels:
    app: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      name: world
      labels:
        app: world
    spec:
      containers:
        - name: world
          image: kubernetes-example-world
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
